### ISSUE TITLE
mmWave x,y,z coordinates generation. 

### ISSUE THREAD

**Issue by eyeris** [HavocFiXer/mmMesh#1]
Hi, I am just wondering about the piece of code that generates the x,y,z coordinates from the mmwave frames.  Appreciate it if you could point that.  

Thank you!

**Comment by HavocFiXer** [comment]
Sorry for the late responds. I just notice the issues tab in GitHub.
As you can see in the repository, the code to generate point cloud from the mmWave IF signal has been uploaded. Hope it helps.

**Comment by rayarindam2111** [comment]
Could you provide a detailed explanation on how this is done with respect to the radar data cube? I'm having a bit of difficulty in comprehending the dimension of the matrices and how they are being processed from the code.

**Comment by HavocFiXer** [comment]
There are some tutorials, basic docs and detailed SDK docs about the mmWave radar on the TI website. You will find them very helpful.

**Comment by rayarindam2111** [comment]
Thank you for the reply. I did go through them, but thought your approach seemed more elegant. Also, I noticed that the point cloud generation formulae in the repository differed slightly from that mentioned in the paper. Could you take a moment to explain the approach adopted in the code?

**Comment by eyeris** [comment]
@HavocFiXer  Thanks a lot! Got it working.

**Comment by HavocFiXer** [comment]
Issue Closed: Uploaded the code to generate point cloud from the mmWave IF signal.
