### ISSUE TITLE
The dataset

### ISSUE THREAD

**Issue by eyeris** [HavocFiXer/mmMesh#2]
Hi, is there any way I can access the dataset?

**Comment by HavocFiXer** [comment]
Sorry. Currently, we are unable to release the dataset.

**Comment by pinjiang** [comment]
Is it possible to release some checkpoint model to do a quick benchmark?

**Comment by HavocFiXer** [comment]
@pinjiang I highly recommend you to use the code to train your own model for evaluation. As you know, there are to coordinate system in experiments, there are the radar coordinate system and the ground truth collecting system (VICON in our work). The calibrations of the two system will be quite different from those in the paper. So, I think the checkpoint model won't help (this is quite different from the natures in the area of CV).

**Comment by HavocFiXer** [comment]
Issue Closed: Currently the dataset is not available, it is highly recommended to use the code to train your own model using your own dataset.
