### ISSUE TITLE
How can the real-time data collection program work?

### ISSUE THREAD

**Issue by zhouwang520** [HavocFiXer/mmMesh#3]
I want to ask the author a question. Nothing happens after the capture.py file is run. My steps are as follows: first connect DCA1000EVM and awr1642, and power on, and finally run capture.py, but the bin file I collected is empty. Do I need to configure the parameters with mmstudio software first, and then run capture.py? I tried but it seems to have failed. Can you give the correct steps to run capture.py? Thanks!

**Comment by HavocFiXer** [comment]
I will write a simple tutorial to explain how to start the radar and use the script to collect data within this week.

**Comment by zhouwang520** [comment]
> I will write a simple tutorial to explain how to start the radar and use the script to collect data within this week.

Thank you very much for your reply, and I hope you can write as much detail as possible, because recently my graduate design has encountered a problem in this place.

**Comment by HavocFiXer** [comment]
Issue Closed: Published a simple tutorial to start the radar and to use the script to collect data in real-time.
