### ISSUE TITLE
What energy in pc_generation.py means?

### ISSUE THREAD

**Issue by kb043** [HavocFiXer/mmMesh#4]
Can you tell me what energy in pc_generation.py means? Is it reflection intensity? thanks

**Comment by HavocFiXer** [comment]
The energy is kind of different from the reflection intensity (like the lidar output). It is the energy of Doppler-FFT after the static clutter removal. With higher energy, it is more likely that there is something are moving with the corresponding speed in a certain distance.

**Comment by HavocFiXer** [comment]
Issue Closed: Explained the energy.
