### ISSUE TITLE
Why the output dim of CombineModule is 68 not 144?

### ISSUE THREAD

**Issue by Chen3110** [HavocFiXer/mmMesh#5]
Hello, 
It is a great work! But there is a question about the output dim of CombineModule in your code. It equals 9*6+3+10+1 that is not same as the num 10+144+1+3 =157 in your paper. Why the num of joints is 9? Wish you could answer me.
Thanks!

**Comment by HavocFiXer** [comment]
Thank you. As mentioned in the Section 5.2.2 and Figure 5 in the paper, in the implementation the locations of VICON markers are not one-on-one mapping with the locations of the SMPL joints. Some SMPL joints has no corresponding markers, and we simply set the rotations of those joints as 0. Thus, in the output of the CombineModule, we only outputs the SMPL joint rotations who has the corresponding markers.

**Comment by Chen3110** [comment]
OK, I see. Thanks for your reply!

**Comment by HavocFiXer** [comment]
Issue Closed: Explained.
