### ISSUE TITLE
Error capturing data from mmWave Radar?

### ISSUE THREAD

**Issue by m-muaz** [HavocFiXer/mmMesh#6]
Hi, I am trying to use your code in 1.mmWave_data_generation to capture the real-time data from the AWR1843BOOST radar but every time I try to read data using getFrame() method it gives me readItem as "wait new frame" and itemNum as -2. Can you tell me could be the possible reason for this? 
I am using the ubuntu 20.04 subsystem for windows 10 as administrator to run capture.py file.

Thanks!

**Comment by HavocFiXer** [comment]
I didn't encounter this problem. I wonder if the computer successfully receive packets from the radar? You can check System Monitor in Ubuntu, find the Network History to see if your computer receives packets from the radar.

**Comment by m-muaz** [comment]
Hi, I want to ask how you are operating the Ti Radar from Ubuntu? I am currently working with Windows since the mmWave Studio is required to initiate frames from radar and that application is currently only supported by Windows?

Thanks!
