### ISSUE TITLE
Converting mmWave data to .dat format

### ISSUE THREAD

**Issue by kevinyao93** [HavocFiXer/mmMesh#7]
I was wondering if I was missing a step - I'm working with some of the .bin files that I get from the mmWave generation, and I was wondering how it goes from these .bin files -> .dat files.  I see in the pc_generation.py, that a Point Cloud is generated, but I was confused on how it gets to the .dat files in the 3.deep_model/data.py. i.e. convert the radar data to the .dat formats (trans.mcl.20p8a) I'm not sure if I missed a step and any help would be appreciated.

**Comment by HavocFiXer** [comment]
Modifying the code provided in the step 2: point cloud generation, you can save the extracted point cloud as a file with any format you want. The generation point cloud file is corresponding to _pc.mcl.20p8a.dat_ in step 3. Hope it helps.

**Comment by kevinyao93** [comment]
I've figured a few things out, but I was wondering which of the 9 joints were the ones that were chosen, and how would I be able to get this data from either SMPL or SMPL+H datasets that I want to test on? I have the mmWave radar to test, but the VICON system is a bit outside of my range, and I was wondering if you could advise on that.

**Comment by HavocFiXer** [comment]
The 9 rotations in includes the global rotation and the rotations of the left/right shoulder/elbow/thigh/knee, which corresponding to the 0,1,2,4,5,16,17,18,19 rotation vector of the theta parameter of SMPL.

**Comment by kevinyao93** [comment]
I'm not entire sure what each of the 9, 3, 3 values represent, at first I thought it was joint, (x,y,z values), and rotational values, but it doesn't seem to actually fit. Could you give me some advice on what corresponds to what for these values? Thanks!

**Comment by HavocFiXer** [comment]
9 denotes a global rotation and eight joint rotations, 3x3 denotes the rotation matrix for the 9 rotations.

**Comment by kevinyao93** [comment]
Ah cool - thanks for the help!
